# Generated by Django 5.1.6 on 2025-04-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_project_end_date_alter_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
