# Generated by Django 5.1.6 on 2025-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_userinfo_job_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
