# Generated by Django 4.2.17 on 2025-05-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_project_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="isPin",
            field=models.BooleanField(default=False),
        ),
    ]
