# Generated by Django 4.2.17 on 2025-05-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0007_message_ispin"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="progress", field=models.IntegerField(default=0),
        ),
    ]
