# Generated by Django 4.2.17 on 2025-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0009_taskhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="percent", new_name="progress",
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
