# Generated by Django 5.1.6 on 2025-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0013_alter_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
